[package]
name = "flex-rs"
version = "0.0.5"
edition = "2021"
build = "build.rs"

[build-dependencies]
windows_exe_info = "0.5.2"

[dependencies]
windows_exe_info = {version = "0.5.2", features = ["manifest"]}
